function [timefig, timetext] = init_timerfig;

	timefig = figure;
	set(timefig, 'DoubleBuffer', 'on', ...
                 'Position', [100 100 200 50], ...
                 'Resize', 'off', ...
                 'MenuBar', 'none', ...
                 'NumberTitle', 'off', ...
                 'Name', 'Time Left ...', ...
                 'Colormap', gray(256));
	timetext = text(0.25,0.5,'Time Left ... ', 'FontSize', 14);         
	axis off;    

    
    