function platedef = pan_plate_metadata(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   HBE4PCTHETCHECKWELLLAYOUT = IMPORTFILE(FILENAME) Reads data from text
%   file FILENAME for the default selection.
%
%   HBE4PCTHETCHECKWELLLAYOUT = IMPORTFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   hbe4pcthetcheckWELLLAYOUT = importfile('hbe4pct_hetcheck_WELL_LAYOUT.csv', 2, 481);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/06/05 13:40:44

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
formatSpec = '%C%C%f%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.


%% Create output variable
platedef = table(dataArray{1:end-1}, 'VariableNames', {'PlateRow','PlateColumn','Well_ID','Object_ID','Object_name','Field_name','Value'});


platedef.PlateRow = [];
platedef.PlateColumn = [];
platedef.Object_name = platedef.Object_name+platedef.Object_ID+'_'+platedef.Field_name;
% platedef.Object_name = categorical(platedef.Object_name);
platedef.Object_ID = [];
platedef.Field_name = [];

platedef = unstack(platedef, 'Value', 'Object_name');

