function [dataout, summary] = pan_load_tracking(filepath, systemid)
% PAN_LOAD_TRACKING loads all tracking files for a panoptes run
%
% Panoptes function 
% 
% This function contains  
% 
% function dataout = pan_load_tracking(filepath, systemid) 
%
% where "dataout" is the outputted data structure for the entire run
%       "filepath" defines the location for tracking data and metadata files
%       "systemid" defines the systed used, is either 'Monoptes' or 'Panoptes'
%       "exityn" if 'y' matlab closes after finishing the analysis
%
% Notes:
% - This function is designed to work within the PanopticNerve software
% chain but can be used manually from the matlab command line interface.
%

% First, set up default values for input parameters in case they are empty 
% or otherwise do not exist.  

video_tracking_constants;

% defaults the single-channel instrument
if nargin < 2 || isempty(systemid)
    systemid = 'monoptes';
end

% does not exit matlab by default when the analysis run is complete
if nargin < 3 || isempty(exityn)
    exityn = 'n';
end

% moving to the path defined as the 'root for the experimental data'
cd(filepath);

% start a timer (to report computation time later on)
tid = tic;

% load the metadata from the appropriate files generated by PanopticNerve
metadata = pan_load_metadata(filepath, systemid, '96well');


filelist = metadata.files.tracking;

Nfiles = length(filelist);

logentry(['Combining ' num2str(Nfiles) ' tracking files.']);

dataout = [];

for k = 1:Nfiles
    [mywell mypass] = pan_wellpass(filelist(k).name);
    
    d = load_video_tracking(filelist(k).name, ...
                        metadata.instr.fps_imagingmode, ...
                        'pixels', 1, ...
                        'absolute', 'no', 'table');
                    

    
    if ~isempty(d)
        numrows = size(d,1);
        
%         d(:,[TIME Z:YAW]) = [];
        
        well_vec = repmat(mywell,numrows,1);
        pass_vec = repmat(mypass,numrows,1);
        
        % summarize the information for each video
        num_trackers = length(unique(d(:,ID)));
        tracker_with_longest_duration = mode(d(:,ID));
        longest_duration = max( d( d(:,ID) == tracker_with_longest_duration, FRAME));
        
        % well, pass, num_trackers, tracker_with_longest_duration, longest_duration
        summary(k,:) = [mywell mypass num_trackers tracker_with_longest_duration longest_duration];
        
        d = [pass_vec well_vec d];
        dataout = [dataout ; d];
        
        
    end
    
end

elapsed_time = toc(tid); 

logentry(['Combining these data files took ' num2str(elapsed_time) ' seconds.']);

% dataout = 0;

return;



% function for writing out stderr log messages
function logentry(txt)
    logtime = clock;
    logtimetext = [ '(' num2str(logtime(1),  '%04i') '.' ...
                   num2str(logtime(2),        '%02i') '.' ...
                   num2str(logtime(3),        '%02i') ', ' ...
                   num2str(logtime(4),        '%02i') ':' ...
                   num2str(logtime(5),        '%02i') ':' ...
                   num2str(floor(logtime(6)), '%02i') ') '];
     headertext = [logtimetext 'pan_load_tracking: '];
     
     fprintf('%s%s\n', headertext, txt);
     
     return;    

return;
