function outs = pan_collect_trajzero_images(filepath, systemid, order_var)

if ~exist('filepath', 'var')
    error('No file defined.'); 
end

if nargin < 3 || isempty(order_var)
    order_var = 'visc'; 
end

video_tracking_constants;

% other parameter settings
plate_type = '96well';
freqtype = 'f';
r = 20;


% load the metadata from the appropriate files generated by PanopticNerve
metadata = pan_load_metadata(filepath, systemid, '96well');


data = load(['matlab_analysis/PM_rheology/' metadata.instr.experiment '.mat']);

% the viscosities are going to include all passes and so every viscosity
% for a particular well will be constant for all passes.
visclist = data.visc_list;

% start working on the fluorescence burst (FLburst) files outtputed by the metadata structure
if ~isempty(metadata.files.FLburst)
    img_filelist = metadata.files.FLburst;
else
    error('No FLburst files to be found.');
end

if ~isempty(metadata.files.tracking)
    traj_filelist = metadata.files.tracking;
else
    error('No tracking files found');
end

collection_dir = 'FL_burst_collection';
mkdir(collection_dir);

metadata_dir = [collection_dir '/metadata'];
mkdir(metadata_dir);

order_var_dir = [metadata_dir '/' order_var];
mkdir(order_var_dir);

collection_file = [metadata.instr.experiment '_' collection_dir];

% fid = fopen([collection_dir '/' collection_file '.txt'], 'w');
fid = fopen([order_var_dir '/' order_var '.txt'], 'w');
fid2 = fopen([order_var_dir '/' 'AllNames'], 'w');

% fprintf(fid, 'image_filename, pass, well, channel, MCU_parameter, visc_Pa.s\n');
png_files = dir([collection_dir '/*.png']);
logentry('Not writing over PNG files that already exist.');

if length(img_filelist) == length(traj_filelist)
    logentry('Same length, everything is fine.');
else
    error('Different number of tracking files compared to first video frames.');
end
    
for k = 1:length(img_filelist)
    
    
    trajfile = traj_filelist(k).name;

    mydir = strrep(trajfile, '_TRACKED.vrpn.mat', '');
    mydir = strrep(mydir, 'video', 'FLburst');
    myfile = 'frame0001.pgm';

    old_FLburst_filename = [mydir '/' myfile];
    new_FLburst_filename = [mydir];
        
    if isempty(png_files)

        im = imread([mydir '/' myfile], 'PGM');    
        im = flipud(im); % because of the different image vs. cartesian axes.
        imfig = figure;
        
        imagesc(im);
        colormap(gray(256));
    
        d = load_video_tracking(trajfile, ...
                    metadata.instr.fps_imagingmode, ...
                    'pixels', 1, ...
                    'absolute', 'no', 'table');
        if isempty(d)
            saveas(imfig, [collection_dir '/' new_FLburst_filename,'_group_1_ellipses', '.png'] , 'png');
            close(imfig);
            continue;
        end
        
        idx = d(:,FRAME) == 1;
        
        first_xys = d(idx,:);
        
        hold on;
            for n = 1:size(first_xys,1)
                h = circle(first_xys(n,X),484-first_xys(n,Y),r,'g');
            end 
        hold off;
        drawnow;
%         pause(0.5);
        
        saveas(imfig, [collection_dir '/' new_FLburst_filename,'_group_1_ellipses', '.png'] , 'png');
        
        close(imfig);
    end
    
    [mywell mypass] = pan_wellpass( mydir );
    
    mychannel = pan_get_channel_id(mywell);
    
    myMCU = metadata.mcuparams.mcu(metadata.mcuparams.well == mywell & ...
                                   metadata.mcuparams.pass == mypass );
                               
    myvisc = visclist(mywell);

    metadata_out(k,:) = [mypass, mywell, mychannel, myMCU, myvisc];
    img_filelist_out{k,1} = new_FLburst_filename;
end

[sorted_metadata, idx] = sortrows(metadata_out, [1 2]);
sorted_img_filelist = img_filelist_out(idx);

switch order_var
    case 'channel'
        values = num2str(sorted_metadata(:,3));
    case 'pass'
        values = num2str(sorted_metadata(:,1));
    case 'well'
        values = num2str(sorted_metadata(:,2));
    case 'MCU'
        values = num2str(sorted_metadata(:,4));
    case 'visc'
        values = num2str(sorted_metadata(:,5), '%10.2e\n');
    otherwise
         error('unknown order_var');        
end


for k = 1:length(img_filelist)
    fprintf(fid, '%s,%s,channel %s#pass %s#well %s#MCU %s#vsc_Pa.s %s\n', ...
                 [sorted_img_filelist{k} '_group_1'], ...
                 values(k,:), ...
                 num2str(sorted_metadata(k,3)), ...
                 num2str(sorted_metadata(k,1)), ...
                 num2str(sorted_metadata(k,2)), ...
                 num2str(sorted_metadata(k,4)), ...
                 num2str(sorted_metadata(k,5),'%10.2e\n'));
             
     fprintf(fid2, '%s,%s\n', ...
                 sorted_img_filelist{k}, ...
                 order_var);
end

fclose(fid);
fclose(fid2);
outs = 0;

return;
 
    
% function for writing out stderr log messages
function logentry(txt)
    logtime = clock;
    logtimetext = [ '(' num2str(logtime(1),  '%04i') '.' ...
                   num2str(logtime(2),        '%02i') '.' ...
                   num2str(logtime(3),        '%02i') ', ' ...
                   num2str(logtime(4),        '%02i') ':' ...
                   num2str(logtime(5),        '%02i') ':' ...
                   num2str(floor(logtime(6)), '%02i') ') '];
     headertext = [logtimetext 'pan_collect_FLburst_images: '];
     
     fprintf('%s%s\n', headertext, txt);
     
     return;    
