


loglog(d_panc.bayes_model_output(1,1).N_curve_struct.tau,  d_panc.bayes_model_output(1,1).N_curve_struct.msd, 'k', ...
       d_panc.bayes_model_output(1,1).D_curve_struct.tau,  d_panc.bayes_model_output(1,1).D_curve_struct.msd, 'y', ...
       d_panc.bayes_model_output(1,1).DA_curve_struct.tau, d_panc.bayes_model_output(1,1).DA_curve_struct.msd, [0 0.5 0], ...
       d_panc.bayes_model_output(1,1).DR_curve_struct.tau, d_panc.bayes_model_output(1,1).DR_curve_struct.msd, 'r', ...
       d_panc.bayes_model_output(1,1).V_curve_struct.tau,  d_panc.bayes_model_output(1,1).V_curve_struct.msd, 'c')
   
   
   loglog(d_panc.bayes_model_output(1,1).N_curve_struct.tau,  d_panc.bayes_model_output(1,1).N_curve_struct.msd, 'k', ...
       d_panc.bayes_model_output(1,1).D_curve_struct.tau,  d_panc.bayes_model_output(1,1).D_curve_struct.msd, 'y', ...
       d_panc.bayes_model_output(1,1).DA_curve_struct.tau, d_panc.bayes_model_output(1,1).DA_curve_struct.msd, [0, 0.5, 0], ...
       d_panc.bayes_model_output(1,1).DR_curve_struct.tau, d_panc.bayes_model_output(1,1).DR_curve_struct.msd, 'r')
   
      loglog(d_panc.bayes_model_output(1,1).N_curve_struct.tau,  d_panc.bayes_model_output(1,1).N_curve_struct.msd, 'k', ...
       d_panc.bayes_model_output(1,1).D_curve_struct.tau,  d_panc.bayes_model_output(1,1).D_curve_struct.msd, 'c', ...
       d_panc.bayes_model_output(1,1).DA_curve_struct.tau, d_panc.bayes_model_output(1,1).DA_curve_struct.msd, 'g', ...
       d_panc.bayes_model_output(1,1).DR_curve_struct.tau, d_panc.bayes_model_output(1,1).DR_curve_struct.msd, 'r')
   
   
         loglog(d_panc.bayes_model_output(2,1).N_curve_struct.tau,  d_panc.bayes_model_output(2,1).N_curve_struct.msd, 'k', ...
       d_panc.bayes_model_output(2,1).D_curve_struct.tau,  d_panc.bayes_model_output(2,1).D_curve_struct.msd, 'm', ...
       d_panc.bayes_model_output(2,1).DA_curve_struct.tau, d_panc.bayes_model_output(2,1).DA_curve_struct.msd, 'g', ...
       d_panc.bayes_model_output(2,1).DR_curve_struct.tau, d_panc.bayes_model_output(2,1).DR_curve_struct.msd, 'b')
   